name: build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: <code_climate_reporter_id>
        with:
          coverageCommand: npm run coverage
          coverageLocations: |
            ${{github.workspace}}/routers/coverage/lcov.info:lcov
            ${{github.workspace}}/models/coverage/lcov.info:lcov
            ${{github.workspace}}/data/coverage/lcov.info:lcov